L = ['Michael', 'Sarah', 'Tracy', 'Bob', 'Jack']
print(L[0:3])
print(L[:3])
print(L[1:3])
#支持L[-1]取倒数第一个元素，那么它同样支持倒数切片
print(L[-2:])
print(L[-2:-1])
#前10个数：
print(L[:10])
#后10个数：
print(L[-10:])
#前11-20个数：
print(L[10:20])
#前10个数，每两个取一个：
print(L[:10:2])
#所有数，每5个取一个
print(L[::5])
#甚至什么都不写，只写[:]就可以原样复制一个list：
print(L[:])